name: sbpy

channels:
    - astropy

dependencies:
    - python>=3 
    - numpy     
    - astropy
    - astropy-helpers
    - Cython
    - matplotlib
    - scipy
    - pip
    - pip:
      - "git+https://github.com/astropy/astroquery.git"
      - ads
      - synphot
