name: sbpy

channels:
    - astropy

dependencies:
    - python>=3.6
    - numpy>=1.4.0
    - astropy>=3.0,<4.0
    - Cython
    - matplotlib
    - scipy
    - pip
    - pip:
      - "git+https://github.com/astropy/astroquery.git"
      - ads
      - synphot>=0.1.2<0.2
      - Sphinx==2.2.1
      - sphinx-astropy
