name: sbpy

channels:
    - astropy

dependencies:
    - python>=3.7
    - numpy>=1.17.0
    - astropy>=5.0
    - Cython
    - matplotlib>=3.0
    - scipy
    - pip
    - pytest
    - pip:
      - astroquery>=0.4.5
      - ads
      - synphot>=1.0.0
      - Sphinx==2.2.1
      - sphinx-astropy>=1.3
