name: sbpy

channels:
    - astropy

dependencies:
    - numpy
    - astropy
    - astropy-helpers
    - Cython
    - matplotlib
    - ads
    - synphot
    - pip
    - pip:
      - git+https://github.com/astropy/astroquery.git
