name: sbpy

channels:
    - astropy

dependencies:
    - numpy
    - astropy
    - astropy-helpers
    - Cython
    - matplotlib
    - ads
    - astroquery
    - synphot
#   - pip:
#       - dependency_from_pip
