name: sbpy

channels:
    - astropy

dependencies:
    - numpy
    - astropy
    - astropy-helpers
    - Cython
    - matplotlib
    - ads
    - https://github.com/astropy/astroquery/archive/master.zip
    - synphot
#   - pip:
#       - dependency_from_pip
