# GitHub Actions workflow that runs on a cron schedule.
# Check URLs and run latest deps with remote tests

name: Weekly CI Tests

on:
  schedule:
    # run at 6am UTC on Mondays
    - cron: '0 6 * * 1'

jobs:
  weekly:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Check links in docs using tox
          toxenv: linkcheck
        - name: Check dev versions of key dependencies
          toxenv: py39-test-devdeps
          toxposargs: --remote-data

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      env:
        ADS_DEV_KEY: ${{ secrets.ADS_DEV_KEY }}
      run: tox ${{ matrix.toxargs}} -e ${{ matrix.toxenv}} -- ${{ matrix.toxposargs}}
