# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

# Remove -numpy126 when we support testing with numpy 2.0

name: CI Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    # branches: # only build on PRs against 'main' if you need to further limit when CI is run.
    #    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARCH_ON_CI: "normal"
  IS_CRON: "false"

jobs:
  oorb-data:
    name: Download OpenOrb data for sbpy testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check for cached files
        id: cache
        uses: actions/cache@v4
        with:
          path: oorb-data/
          key: oorb-data
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Set download location
        run: |
          echo "OORB_DATA=$GITHUB_WORKSPACE/oorb-data" >> "$GITHUB_ENV"
      - name: Download ephemeris, time, and observatory data
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p "$OORB_DATA"
          python3 .github/scripts/download-oorb-data.py
      - name: Cache data
        uses: actions/cache@v4
        with:
          path: oorb-data/
          key: oorb-data
  tests:
    needs: [oorb-data]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      setenv: |
        ARCH_ON_CI: "normal"
        IS_CRON: "false"
        OORB_DATA: "$GITHUB_WORKSPACE/oorb-data/"
      cache-path: oorb-data/
      cache-key: oorb-data
      submodules: false
      coverage: ""
      envs: |
        - name: Code style checks
          linux: codestyle

        - name: Python 3.11 with minimal dependencies, measuring coverage
          linux: py311-test-numpy126-cov
          coverage: codecov

        - name: Python 3.10 with all optional dependencies, measuring coverage
          linux: py310-test-numpy126-alldeps-cov
          coverage: codecov

        - name: Python 3.11 with all optional dependencies (MacOS)
          macos: py311-test-numpy126-alldeps
          runs-on: macos-13

        - name: Python 3.9 with oldest supported versions
          linux: py39-test-oldestdeps
