# GitHub Actions workflow for testing and continuous integration.
#
# This file performs testing using tox and tox.ini to define and configure the test environments.

# Remove -numpy126 when we support testing with numpy 2.0

name: CI Tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    # branches: # only build on PRs against 'main' if you need to further limit when CI is run.
    #    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ARCH_ON_CI: "normal"
  IS_CRON: "false"

jobs:
  # Github Actions supports ubuntu, windows, and macos virtual environments:
  # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      setenv: |
        ARCH_ON_CI: "normal"
        IS_CRON: "false"
      runs-on: |
        macos: macos-13
      submodules: false
      coverage: ""
      envs: |
        - name: Code style checks
          linux: codestyle

        - name: Python 3.11 with minimal dependencies, measuring coverage
          linux: py311-test-numpy126-cov
          coverage: codecov

        - name: Python 3.10 with all optional dependencies, measuring coverage
          linux: py310-test-numpy126-alldeps-cov
          coverage: codecov

        - name: Python 3.11 with all optional dependencies (MacOS)
          macos: py311-test-numpy126-alldeps

        - name: Python 3.9 with oldest supported versions
          linux: py39-test-oldestdeps
